
DROP FUNCTION IF EXISTS `__DBNAME__`.`bcpy_KvDB_encTableMeta`;
/*COMMIT*/
CREATE FUNCTION `__DBNAME__`.`bcpy_KvDB_encTableMeta`(pTable VARCHAR(128))
RETURNS VARCHAR(128) DETERMINISTIC
BEGIN
    RETURN CONCAT(pTable, '_meta');
END 
/*COMMIT*/

DROP FUNCTION IF EXISTS `__DBNAME__`.`bcpy_KvDB_encTableList`;
/*COMMIT*/
CREATE FUNCTION `__DBNAME__`.`bcpy_KvDB_encTableList`(pTable VARCHAR(128))
RETURNS VARCHAR(128) DETERMINISTIC
BEGIN
    RETURN CONCAT(pTable, '_list');
END 
/*COMMIT*/

DROP FUNCTION IF EXISTS `__DBNAME__`.`bcpy_KvDB_encTableLog`;
/*COMMIT*/
CREATE FUNCTION `__DBNAME__`.`bcpy_KvDB_encTableLog`(pTable VARCHAR(128))
RETURNS VARCHAR(128) DETERMINISTIC
BEGIN
    RETURN CONCAT(pTable, '_log');
END 
/*COMMIT*/

